# SPDX-FileCopyrightText: 2026 Kalle Erlhoff
# SPDX-License-Identifier: Apache-2.0

"""Initial schema

The whole schema in one step, and deliberately so: the three revisions before it were folded
into this one on 2026-08-03. At that point no device had ever run Kiekmap, so no database
existed that a migration path could have led anywhere from -- a history that nothing can replay
is not a history, it is ballast.

**From the first Pi onwards this stops being allowed.** Once a museum has a filled database, the
only way its data can survive a schema change is the chain of migrations. See docs/decisions.md.

Two of the folded revisions are worth remembering rather than the files themselves:

  * house numbers on ``places`` -- ``street`` and ``housenumber``, filled only for
    ``kind="adresse"``
  * ``status`` renamed from ``hidden`` to ``deleted``. That one **destroyed data**: rebuilding
    the table with foreign keys switched on took every visitor contribution with it. What came of
    that is the ``PRAGMA foreign_keys=OFF`` in ``alembic/env.py`` and the test in
    ``tests/test_migrations.py``; both stay, the migration file does not.

Revision ID: 1cf9ccd28cd7
Revises:
Create Date: 2026-08-03 12:38:18.367624
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1cf9ccd28cd7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("date_precision", sa.String(length=10), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("place_name", sa.String(length=300), nullable=True),
        sa.Column("location_accuracy_m", sa.Integer(), nullable=True),
        sa.Column("credit", sa.String(length=200), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("title_source", sa.String(length=10), nullable=True),
        sa.Column("date_source", sa.String(length=10), nullable=True),
        sa.Column("location_source", sa.String(length=10), nullable=True),
        sa.Column("exif_datetime", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.CheckConstraint(
            "date_precision IN ('day', 'month', 'year', 'decade', 'unknown')", name="ck_precision"
        ),
        sa.CheckConstraint("status IN ('published', 'deleted')", name="ck_status"),
        sa.CheckConstraint("(lat IS NULL) = (lon IS NULL)", name="ck_coordinate_pair"),
        sa.CheckConstraint("date_to IS NULL OR date_from <= date_to", name="ck_date_order"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index("ix_photos_location", ["lat", "lon"], unique=False)
        batch_op.create_index("ix_photos_status", ["status"], unique=False)
        batch_op.create_index("ix_photos_time", ["date_from", "date_to"], unique=False)

    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_normalized", sa.String(length=200), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("housenumber", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "kind", "lat", "lon", name="uq_place"),
    )
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.create_index("ix_places_search", ["name_normalized"], unique=False)
        batch_op.create_index("ix_places_street", ["street"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("reverted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("source IN ('exif', 'curator', 'visitor')", name="ck_change_source"),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("changes", schema=None) as batch_op:
        batch_op.create_index("ix_changes_created", ["created_at"], unique=False)
        batch_op.create_index("ix_changes_photo", ["photo_id"], unique=False)

    op.create_table(
        "import_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("photo_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('imported', 'duplicate', 'rejected')", name="ck_import_result"
        ),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_log", schema=None) as batch_op:
        batch_op.create_index("ix_import_log_created", ["created_at"], unique=False)

    op.create_table(
        "photo_tags",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("photo_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photo_tags")
    with op.batch_alter_table("import_log", schema=None) as batch_op:
        batch_op.drop_index("ix_import_log_created")

    op.drop_table("import_log")
    with op.batch_alter_table("changes", schema=None) as batch_op:
        batch_op.drop_index("ix_changes_photo")
        batch_op.drop_index("ix_changes_created")

    op.drop_table("changes")
    op.drop_table("tags")
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index("ix_places_street")
        batch_op.drop_index("ix_places_search")

    op.drop_table("places")
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index("ix_photos_time")
        batch_op.drop_index("ix_photos_status")
        batch_op.drop_index("ix_photos_location")

    op.drop_table("photos")
    # ### end Alembic commands ###
